### ISSUE TITLE
Error: recovery id invalid at Signature.recoverPublicKey

### ISSUE THREAD

**Issue by m-gunes** [ethereum/js-ethereum-cryptography#95] opened 2023-10-04 13:52 UTC
```javascript
// Client

function signMessage(message, privateKey){
  const msgHash = keccak256(utf8ToBytes(message));
  const signature = secp256k1.sign(msgHash, privateKey); 
  console.log('signature', signature); // {r: 1234.., s:5677.., recovery: 1}
  return signature.toCompactHex();
}

```
The client sends the signature in hex format.

```javascript
// Server

  const msgHash = keccak256(utf8ToBytes(String(amount)));
  const sig = secp256k1.Signature.fromCompact(signature);
  console.log("sig", sig); // {r: 1234.., s:5677.., recovery: undefined}
  const publicKey = sig.recoverPublicKey(msgHash).toRawBytes();

```
To recover the publicKey, after applying fromCompact function, the signature recovery property becomes undefined (expecting 1) and recoverPublicKey() throw error: ```recovery id invalid.```

In this scenario I solved the problem in the server by adding the recovery bit.

```javascript
 const sig = secp256k1.Signature.fromCompact(signature).addRecoveryBit(1);
```

I'm really not sure if this is a problem or if the way I'm sending signatures from client to server is correct. This is my first time using the library and I'm trying to learn more about it. Can someone tell me what's going on?

By the way, I would be happy if someone could share some documentations about the library. I couldn't find it.

**Comment by paulmillr** [comment] 2023-10-05 04:48
>The `secp256k1` submodule provides a library for elliptic curve operations on
the curve secp256k1. For detailed documentation, follow [README of `noble-curves`](https://github.com/paulmillr/noble-curves), which the module uses as a backend.

Here's the quote from README.

The recovery bit is not serialized by design, because it's not standard. So, you need to preserve recovery bit somewhere if you're transferring it with the signature. Ethereum usually has recovery bit specified in `v` value of `transaction`.

**Closed** 2023-10-05 04:48 UTC
